# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1021, 611)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1021, 611))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Database.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(9, 36, 133, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(160, 40, 81, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(264, 30, 151, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 32, 61, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(9, 65, 133, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 60, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(9, 94, 131, 20))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 90, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 90, 71, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 122, 38, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 120, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(9, 152, 401, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 148, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(530, 151, 49, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(9, 180, 73, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 177, 75, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.checkBox_3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(530, 180, 55, 17))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(9, 210, 401, 20))
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(440, 62, 281, 20))
        self.lineEdit_7.setText(_fromUtf8(""))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(-1, 236, 1021, 371))
        self.textBrowser.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser.setLineWidth(2)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(740, 40, 75, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(740, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(740, 80, 75, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(830, 80, 171, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.pushButton_11 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(740, 110, 75, 23))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 241))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pushButton_12 = QtGui.QPushButton(self.frame)
        self.pushButton_12.setGeometry(QtCore.QRect(260, 60, 75, 23))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_15 = QtGui.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(260, 90, 75, 23))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.frame)
        self.pushButton_16.setGeometry(QtCore.QRect(260, 120, 75, 23))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(430, 0, 301, 241))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.pushButton_13 = QtGui.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 206, 75, 23))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_7 = QtGui.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 206, 75, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.checkBox_4 = QtGui.QCheckBox(self.frame_2)
        self.checkBox_4.setGeometry(QtCore.QRect(160, 180, 55, 17))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.comboBox_3 = QtGui.QComboBox(self.frame_2)
        self.comboBox_3.setGeometry(QtCore.QRect(210, 180, 31, 20))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_4 = QtGui.QComboBox(self.frame_2)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 110, 281, 22))
        self.comboBox_4.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(730, 0, 291, 241))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pushButton_9 = QtGui.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(200, 210, 75, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_14 = QtGui.QPushButton(self.frame_3)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_17 = QtGui.QPushButton(self.frame_3)
        self.pushButton_17.setGeometry(QtCore.QRect(100, 40, 75, 23))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_18 = QtGui.QPushButton(self.frame_3)
        self.pushButton_18.setGeometry(QtCore.QRect(10, 180, 75, 23))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_19 = QtGui.QPushButton(self.frame_3)
        self.pushButton_19.setGeometry(QtCore.QRect(200, 40, 75, 23))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(150, 130, 51, 61))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.calendarWidget = QtGui.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 260, 421, 281))
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(630, 240, 341, 191))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.lineEdit_4 = QtGui.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 60, 301, 20))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 90, 301, 20))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.radioButton = QtGui.QRadioButton(self.widget)
        self.radioButton.setGeometry(QtCore.QRect(30, 120, 45, 17))
        self.radioButton.setAutoExclusive(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton)
        self.pushButton_22 = QtGui.QPushButton(self.widget)
        self.pushButton_22.setGeometry(QtCore.QRect(260, 150, 75, 23))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.radioButton_2 = QtGui.QRadioButton(self.widget)
        self.radioButton_2.setGeometry(QtCore.QRect(115, 120, 44, 17))
        self.radioButton_2.setAutoExclusive(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_4 = QtGui.QRadioButton(self.widget)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 150, 49, 17))
        self.radioButton_4.setAutoExclusive(True)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButton_4)
        self.radioButton_3 = QtGui.QRadioButton(self.widget)
        self.radioButton_3.setGeometry(QtCore.QRect(115, 150, 61, 17))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.lineEdit_9 = QtGui.QLineEdit(self.widget)
        self.lineEdit_9.setGeometry(QtCore.QRect(30, 20, 301, 20))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(480, 430, 341, 191))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.lineEdit_10 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(30, 50, 151, 20))
        self.lineEdit_10.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_10.setReadOnly(False)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_11 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(200, 50, 131, 20))
        self.lineEdit_11.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_11.setReadOnly(False)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.pushButton_23 = QtGui.QPushButton(self.widget_2)
        self.pushButton_23.setGeometry(QtCore.QRect(260, 150, 75, 23))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.lineEdit_12 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(30, 20, 301, 20))
        self.lineEdit_12.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_12.setReadOnly(False)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.pushButton_24 = QtGui.QPushButton(self.widget_2)
        self.pushButton_24.setGeometry(QtCore.QRect(170, 150, 75, 23))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.lineEdit_13 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(30, 80, 151, 20))
        self.lineEdit_13.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.lineEdit_13.setText(_fromUtf8(""))
        self.lineEdit_13.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_13.setReadOnly(False)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(200, 80, 131, 20))
        self.lineEdit_14.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_14.setReadOnly(False)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.widget.raise_()
        self.widget_2.raise_()
        self.calendarWidget.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.checkBox.raise_()
        self.pushButton.raise_()
        self.label_6.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.comboBox.raise_()
        self.pushButton_3.raise_()
        self.label_7.raise_()
        self.label_2.raise_()
        self.pushButton_4.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_5.raise_()
        self.checkBox_2.raise_()
        self.label_5.raise_()
        self.pushButton_6.raise_()
        self.checkBox_3.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.textBrowser.raise_()
        self.pushButton_8.raise_()
        self.label_4.raise_()
        self.pushButton_10.raise_()
        self.comboBox_2.raise_()
        self.pushButton_11.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Form1", None))
        self.label.setText(_translate("MainWindow", "Databases Info", None))
        self.label_3.setText(_translate("MainWindow", "Client Info", None))
        self.checkBox.setText(_translate("MainWindow", "Force Trunk", None))
        self.pushButton.setText(_translate("MainWindow", "Enum Rev", None))
        self.label_6.setText(_translate("MainWindow", "Client path", None))
        self.pushButton_2.setText(_translate("MainWindow", "Update", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "HRM_Trunk", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "HRM_Release", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "AGN_Trunk", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "AGN_Release", None))
        self.pushButton_3.setText(_translate("MainWindow", "Run", None))
        self.label_7.setText(_translate("MainWindow", "Server config", None))
        self.label_2.setText(_translate("MainWindow", "DB Path", None))
        self.pushButton_4.setText(_translate("MainWindow", "STOP", None))
        self.pushButton_5.setText(_translate("MainWindow", "Start", None))
        self.checkBox_2.setText(_translate("MainWindow", "Trunk", None))
        self.label_5.setText(_translate("MainWindow", "DB Server Path", None))
        self.pushButton_6.setText(_translate("MainWindow", "Update", None))
        self.checkBox_3.setText(_translate("MainWindow", "Server", None))
        self.pushButton_8.setText(_translate("MainWindow", "Redmine", None))
        self.label_4.setText(_translate("MainWindow", "API TOOLS", None))
        self.pushButton_10.setText(_translate("MainWindow", "Jenkins", None))
        self.pushButton_11.setText(_translate("MainWindow", "Build", None))
        self.pushButton_12.setText(_translate("MainWindow", "Clear !!!", None))
        self.pushButton_15.setText(_translate("MainWindow", "Deploy", None))
        self.pushButton_16.setText(_translate("MainWindow", "Uninstall !!!", None))
        self.pushButton_13.setText(_translate("MainWindow", "STOP", None))
        self.pushButton_7.setText(_translate("MainWindow", "ClrLocalData", None))
        self.checkBox_4.setText(_translate("MainWindow", "Client", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3", None))
        self.pushButton_9.setText(_translate("MainWindow", "ClrLog", None))
        self.pushButton_14.setText(_translate("MainWindow", "Queue", None))
        self.pushButton_17.setText(_translate("MainWindow", "Calendar", None))
        self.pushButton_18.setText(_translate("MainWindow", "ESSLog", None))
        self.pushButton_19.setText(_translate("MainWindow", "OPTIONS", None))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "DB Server Path", None))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "DB Data Path", None))
        self.radioButton.setText(_translate("MainWindow", "HRM", None))
        self.pushButton_22.setText(_translate("MainWindow", "Deploy", None))
        self.radioButton_2.setText(_translate("MainWindow", "AGN", None))
        self.radioButton_4.setText(_translate("MainWindow", "Trunk", None))
        self.radioButton_3.setText(_translate("MainWindow", "Release", None))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "DB Name", None))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "Jenkins Username", None))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "Jenkins Password", None))
        self.pushButton_23.setText(_translate("MainWindow", "Save", None))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "Redmine API KEY", None))
        self.pushButton_24.setText(_translate("MainWindow", "Clear", None))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "ESS Username", None))
        self.lineEdit_14.setPlaceholderText(_translate("MainWindow", "ESS Password", None))

