# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1021, 611)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1021, 611))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(9, 36, 133, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(160, 40, 81, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 30, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 32, 41, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(9, 65, 133, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 60, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(9, 94, 131, 20))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 90, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 90, 49, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 122, 38, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 120, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(9, 152, 401, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 148, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(530, 151, 49, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(9, 180, 73, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 177, 75, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.checkBox_3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(530, 180, 55, 17))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(9, 210, 401, 20))
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(440, 62, 281, 20))
        self.lineEdit_7.setText(_fromUtf8(""))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(440, 120, 281, 20))
        self.lineEdit_8.setText(_fromUtf8(""))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(-1, 236, 1021, 371))
        self.textBrowser.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser.setLineWidth(2)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(740, 40, 75, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(740, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(740, 80, 75, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(830, 80, 151, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.pushButton_11 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(740, 110, 75, 23))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 241))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pushButton_12 = QtGui.QPushButton(self.frame)
        self.pushButton_12.setGeometry(QtCore.QRect(260, 60, 75, 23))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_15 = QtGui.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(260, 90, 75, 23))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.frame)
        self.pushButton_16.setGeometry(QtCore.QRect(260, 120, 75, 23))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(430, 0, 301, 241))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.pushButton_13 = QtGui.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 206, 75, 23))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_7 = QtGui.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 206, 75, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(730, 0, 291, 241))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pushButton_9 = QtGui.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(200, 210, 75, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_14 = QtGui.QPushButton(self.frame_3)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.progressBar = QtGui.QProgressBar(self.frame_3)
        self.progressBar.setGeometry(QtCore.QRect(100, 110, 151, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.checkBox.raise_()
        self.pushButton.raise_()
        self.label_6.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.comboBox.raise_()
        self.pushButton_3.raise_()
        self.label_7.raise_()
        self.label_2.raise_()
        self.pushButton_4.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_5.raise_()
        self.checkBox_2.raise_()
        self.label_5.raise_()
        self.pushButton_6.raise_()
        self.checkBox_3.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_8.raise_()
        self.textBrowser.raise_()
        self.pushButton_8.raise_()
        self.label_4.raise_()
        self.pushButton_10.raise_()
        self.comboBox_2.raise_()
        self.pushButton_11.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Form1", None))
        self.label.setText(_translate("MainWindow", "Databases Info", None))
        self.label_3.setText(_translate("MainWindow", "Client Info", None))
        self.checkBox.setText(_translate("MainWindow", "Force Trunk", None))
        self.pushButton.setText(_translate("MainWindow", "Enum Rev", None))
        self.label_6.setText(_translate("MainWindow", "Cllocal", None))
        self.pushButton_2.setText(_translate("MainWindow", "Update", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "HRM_Trunk", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "HRM_Release", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "AGN_Trunk", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "AGN_Release", None))
        self.pushButton_3.setText(_translate("MainWindow", "Run", None))
        self.label_7.setText(_translate("MainWindow", "ClRemote", None))
        self.label_2.setText(_translate("MainWindow", "DB Path", None))
        self.pushButton_4.setText(_translate("MainWindow", "STOP", None))
        self.pushButton_5.setText(_translate("MainWindow", "Start", None))
        self.checkBox_2.setText(_translate("MainWindow", "Trunk", None))
        self.label_5.setText(_translate("MainWindow", "DB Server Path", None))
        self.pushButton_6.setText(_translate("MainWindow", "Update", None))
        self.checkBox_3.setText(_translate("MainWindow", "Server", None))
        self.pushButton_8.setText(_translate("MainWindow", "Redmine", None))
        self.label_4.setText(_translate("MainWindow", "API TOOLS", None))
        self.pushButton_10.setText(_translate("MainWindow", "Jenkins", None))
        self.pushButton_11.setText(_translate("MainWindow", "Build", None))
        self.pushButton_12.setText(_translate("MainWindow", "Clear !!!", None))
        self.pushButton_15.setText(_translate("MainWindow", "Deploy", None))
        self.pushButton_16.setText(_translate("MainWindow", "Uninstall !!!", None))
        self.pushButton_13.setText(_translate("MainWindow", "STOP", None))
        self.pushButton_7.setText(_translate("MainWindow", "ClrLocalData", None))
        self.pushButton_9.setText(_translate("MainWindow", "ClrLog", None))
        self.pushButton_14.setText(_translate("MainWindow", "Queue", None))

